fuse -> ROS 2 fuse_core: Linting
locusrobotics/fuse pull request #292
Opened 2022-12-01 06:00 UTC by methylDragon

See: #276

# Description

- Fixes linting. Nuff said.
- Also migrates `.h` files to `.hpp` files!

Lots of files got changed!

It's a wrap for fuse_core (at least until we need to circle back for waitables)
Pinging @svwilliams for visibility.

2022-12-01 19:02 UTC, sloretz requested changes

2022-12-01 19:02 UTC, sloretz commented on fuse_doc/doc/.templates/full_globaltoc.html
> -    <li class="toctree-l1"><a href="../../fuse_core/api/index.html"/>fuse_core</a></li>
This one looks like an accidental find/replace

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/node_interfaces/node_interfaces.h
> +#include <fuse_core/node_interfaces/node_interfaces.hpp>
I don't think we need a `.h` migration header for this one since we just added the file in the last PR. There isn't any downstream code including it that would benefit.

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/node_interfaces/node_interfaces_helpers.h
> +#include <fuse_core/node_interfaces/node_interfaces_helpers.hpp>
Same comment about not needing a `.h` migration header for this one

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/time.h
> +#warning This header is obsolete, please include fuse_core/time.hpp instead
Same comment about not needing a migration header for this one since we just added it.

2022-12-01 19:02 UTC, sloretz commented on fuse_core/test/test_timestamp_manager.cpp
> +  // |------********-----------------------> t Expected: |------********-----------------------> t
I think these comments got a little messed up in the reformatting. The newlines seem to be intentional for showing a timeline

2022-12-01 19:02 UTC, sloretz commented on fuse_core/test/test_timestamp_manager.cpp
> +  // |------********-----------------------> t Expected: |------********-----------------------> t
There are a bunch more places like this in this file below.

2022-12-01 19:02 UTC, sloretz commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.0;
I think the formatting was intentional before to line up the numbers in the matrix

2022-12-01 19:02 UTC, sloretz commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.2, 0.0;
Same comment about the formatting being intentional here

2022-12-01 19:02 UTC, sloretz commented on fuse_core/src/graph_deserializer.cpp
> +  // Load all known plugin libraries I believe the library containing a given Variable or Constraint
Maybe add a period after `Load all known plugin libraries`

2022-12-01 19:02 UTC, sloretz commented on fuse_core/src/transaction_deserializer.cpp
> +  // Load all known plugin libraries I believe the library containing a given Variable or Constraint
same comment about adding a period here.

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/autodiff_local_parameterization.hpp
> + * Plus(x, delta) -> x_plus_delta
I think this line being indented before was intentional

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/autodiff_local_parameterization.hpp
> + * Minus(x1, x2) -> delta
Same comment about how the indentation here before was intentional

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/ceres_macros.hpp
> +  (CERES_VERSION_MINOR > y || (CERES_VERSION_MINOR >= y && \
Indentation here before looked intentional. Would the linter be unhappy if we restored it?

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/console.hpp
> +    last_hit_ = time_point_cast<milliseconds>(std::chrono::system_clock::from_time_t(-1));
Is there a test covering this code? I would have expected an error because of `milliseconds` instead of `std::chrono::milliseconds` (same above).

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/graph.hpp
> +   * TODO(efernandez) support jacobian output argument The jacobian output argument is not
I think a period should be added here too

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/message_buffer_impl.hpp
> +  // Remove buffer elements before the expiration time. Be careful to ensure that:  - at least two
I think the newlines for the list were intentional here

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/parameter.hpp
> + * @param[in] When `true`, the parameter override is ignored. Default to `false`. \return The
I think this line is missing the parameter name `ignore_override`

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/parameter.hpp
> + *                  value of the parameter. @throws if the parameter has already been declared
`@throws` should probably be a separate line

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/parameter.hpp
> + * @param[out] value - The ROS parameter value for the \p key @throws std::runtime_error if the
same comment about `@throws` - it might be worth grepping for `@throws` to double check them if a script was used to change this one

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/transaction.hpp
> +#include <boost/archive/binary_oarchive.hpp>
Is this include unused? It seems to be new in this PR but none of the `boost::` things in this file look like they come from it.

2022-12-01 19:02 UTC, sloretz commented on fuse_core/include/fuse_core/util.hpp
> +  // Handle the 1*Tau roll-over (https://tauday.com/tau-manifesto) Use ceres::floor because it is
Recommend period or newline here

2022-12-01 19:43 UTC, methylDragon commented on fuse_core/include/fuse_core/parameter.hpp
> + * @param[out] value - The ROS parameter value for the \p key @throws std::runtime_error if the
Ah, an edge case I did not account for in the script

2022-12-01 19:44 UTC, methylDragon commented on fuse_core/include/fuse_core/transaction.hpp
> +#include <boost/archive/binary_oarchive.hpp>
Because of the include reordering, I needed to add this in, otherwise one of the boost serialization libraries complains about a missing method.

(The issue used to be masked by fuse_core/serialization.hpp being included first, but that can't happen without making cpplint unhappy.)

2022-12-01 19:52 UTC, methylDragon commented on fuse_doc/doc/.templates/full_globaltoc.html
> -    <li class="toctree-l1"><a href="../../fuse_core/api/index.html"/>fuse_core</a></li>
Whoa

2022-12-01 19:54 UTC, methylDragon commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.2, 0.0;
Hmm, I think this edge case is going to have to stay (for manual fixing...)
I'm not sure how to implement logic to parse this case

2022-12-01 20:01 UTC, methylDragon commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.2, 0.0;
Oh actually this was done by uncrustify reformat :OOOOOOOO

2022-12-01 20:02 UTC, methylDragon commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.2, 0.0;
I'm going to need to use a bypassing directive for uncrustify. I'll add it in and fix the formatting

2022-12-01 20:04 UTC, sloretz commented on fuse_core/test/test_local_parameterization.cpp
> +    0.0, 0.2, 0.0;
+1 to manually fixing instead of trying to make automation do 100%

2022-12-01 20:04 UTC, sloretz commented on fuse_core/include/fuse_core/transaction.hpp
> +#include <boost/archive/binary_oarchive.hpp>
Ah got it. Sounds like a bug in Boost then.

2022-12-01 20:12 UTC, methylDragon commented on fuse_core/src/graph_deserializer.cpp
> +  // Load all known plugin libraries I believe the library containing a given Variable or Constraint
This is an edge case of my script with greedy wrapping. I'll edit it and have the script only start wrapping once it encounters a block that's long (which means short lines prior to those won't get smashed together)

2022-12-01 20:58 UTC, methylDragon commented on fuse_core/include/fuse_core/autodiff_local_parameterization.hpp
> + * Plus(x, delta) -> x_plus_delta
Script has been updated to now catch this edge-case. But I'll have to manually fix these in this package.

2022-12-01 20:59 UTC, methylDragon commented on fuse_core/include/fuse_core/ceres_macros.hpp
> +  (CERES_VERSION_MINOR > y || (CERES_VERSION_MINOR >= y && \
This is uncrustify automatically doing it. I'll add a bypass directive.

2022-12-01 21:07 UTC, methylDragon commented on fuse_core/include/fuse_core/console.hpp
> +    last_hit_ = time_point_cast<milliseconds>(std::chrono::system_clock::from_time_t(-1));
That's strange. Something like this shouldn't compile, yet it compiles fine locally.. Maybe a dirty workspace?

Ah, it never gets used in fuse_core, only in fuse_publishers (currently `COLCON_IGNORED`, so the error would only come up then.

Nice catch!

2022-12-01 22:54 UTC, sloretz approved these changes
LGTM and all tests in fuse_core pass locally using Rolling deps from the testing repo on Jammy

2022-12-01 23:00 UTC, merged

2022-12-16 22:25 UTC, svwilliams commented on fuse_core/include/fuse_core/transaction.hpp
> +#include <boost/archive/binary_oarchive.hpp>
Sorry. I'm behind on my email.

I just want to note that the boost serialization system can be particular about when/where includes happen. Specifically the input/output archives must be included before any BOOST_CLASS_EXPORT macros are used.

https://www.boost.org/doc/libs/1_71_0/libs/serialization/doc/special.html#export
> BOOST_CLASS_EXPORT in the same source module that includes any of the archive class headers will instantiate code required to serialize polymorphic pointers of the indicated type to the all those archive classes. If no archive class headers are included, then no code will be instantiated.
>
> Note that the implemenation of this functionality requires that the BOOST_CLASS_EXPORT macro appear after the inclusion of any archive class headers for which code is to be instantiated. So, code that uses BOOST_CLASS_EXPORT will look like the following:
>
>```
> #include <boost/archive/text_oarchive.hpp>
> #include <boost/archive/text_oarchive.hpp>
> ... // other archives
> 
> #include "a.hpp" // header declaration for class a
> BOOST_CLASS_EXPORT(a)
> ... // other class headers and exports
> ```