fuse -> ROS 2 fuse_models: Linting
locusrobotics/fuse pull request #315
Opened 2023-01-28 09:45 UTC by methylDragon

See: #276
Depends on: #314

Linting
Migrates .h to .hpp
Pinging @svwilliams for visibility.

Note: There's an open question about what to do about test_unicycle_2d.cpp and test_sensor_proc.cpp's proprietary copyright licenses (to fix ament_copyright)

2023-01-28 16:17 UTC, methylDragon commented
Note @svwilliams : Two files had to get excluded from linting: https://github.com/locusrobotics/fuse/pull/315/commits/e62784bcced763575354e6fe2f29b2f29e196371

This is because they featured copyright docstrings with proprietary copyrights.

E.g. https://github.com/methylDragon/fuse/blob/rolling-models-linting/fuse_models/test/test_sensor_proc.cpp
```
/***************************************************************************
 * Copyright (C) 2019 Clearpath Robotics. All rights reserved.
 * Unauthorized copying of this file, via any medium, is strictly prohibited
 * Proprietary and confidential
 ***************************************************************************/
```

2023-01-29 23:51 UTC, sloretz requested changes
All tests in fuse_publishers and fuse_models pass for me locally. When these comments are addressed LGTM

2023-01-29 23:51 UTC, sloretz commented on fuse_models/include/fuse_models/imu_2d.hpp
> + * orientation constraints. 2. Creates 2D velocity variables and constraints.
nit, newline to keep list structure.

2023-01-29 23:51 UTC, sloretz commented on fuse_models/include/fuse_models/odometry_2d.hpp
> + * is set to true, consecutive measurements will be used to generate relative pose constraints. 2.
same comment about new line to keep list structure.

2023-01-29 23:51 UTC, sloretz commented on fuse_models/include/fuse_models/unicycle_2d_state_cost_function.hpp
> +   *                         at index 0, y at index 1) 6 : yaw2 - Second yaw 7 : vel_linear2 -
Newlines to preserve list structure here

2023-01-29 23:51 UTC, sloretz commented on fuse_models/include/fuse_models/unicycle_2d_state_cost_function.hpp
> +      // jacobian.applyOnTheLeft(-A_); } }
Newlines to preserve code example here

2023-01-30 03:53 UTC, merged