Gcc12 ceres 2.1.0 manifold locus
locusrobotics/fuse pull request #363
Opened 2024-03-28 04:24 UTC by svwilliams

Additional fixes and cleanup for #341

2024-04-01 19:13 UTC, needphpsql commented
Let's consider some use case:
1. User has existing code using fuse before this PR.
  In some day later, the user's ceres is upgraded to 2.1 or 2.2. The user's source code doesn't need to change, however, they need to update the fuse library to get this PR and rebuild their program.
2. User creates new code using the new fuse with this PR merged.
  In this condition, does the user need to use any new method to create their functions to use manifold class? Or they only need to use the fuse like before this PR?

2024-04-01 19:14 UTC, needphpsql approved these changes
No more comments other than the questions mentioned

2024-04-01 21:32 UTC, svwilliams commented
> Let's consider some use case:

1. Correct. Ubuntu 24.04 will ship with Ceres 2.2. For this case, fuse will already be compiled with Manifold support. But for any older OS, fuse will be compiled without manifold support by default. If the user updates their local version of Ceres Solver to 2.1 or later, then the user will also need to download and compile `fuse` from source code. I can't think of a way around this.
2. If the user code does not include any custom variable types, then the `fuse` interface remains unchanged. If the user code does include a custom variable, then I would recommend implementing the `monifold()` interface instead of the `localParameterization()`. However, this is not required. Newly created variables with `localParameterization()` functions will continue to operate correctly and automatically through the ManifoldAdapter class.

2024-04-02 02:34 UTC, carlos-m159 commented on fuse_models/test/test_unicycle_2d_state_cost_function.cpp
> +#include <fuse_core/ceres_macros.h>
I don't think you need this here

2024-04-02 14:01 UTC, DavidLocus approved these changes

2024-04-02 17:12 UTC, efernandez requested changes
LGTM, just two minor comments

2024-04-02 17:12 UTC, efernandez commented on fuse_constraints/include/fuse_constraints/marginal_constraint.h
>  #include <string>
```suggestion
#include <stdexcept>
#include <string>
```
required by `std::runtime_error`

2024-04-02 17:12 UTC, efernandez commented on fuse_constraints/include/fuse_constraints/marginal_cost_function.h
> +   * @param[in] manifolds               The manifold associated with the variable
```suggestion
   * @param[in] A         The A matrix of the marginal cost (of the form A*(x - x_bar) + b)
   * @param[in] b         The b vector of the marginal cost (of the form A*(x - x_bar) + b)
   * @param[in] x_bar     The linearization point of the involved variables
   * @param[in] manifolds The manifold associated with the variable
```

2024-04-03 01:16 UTC, carlos-m159 approved these changes

2024-04-03 01:16 UTC, carlos-m159 commented on fuse_models/test/test_unicycle_2d_state_cost_function.cpp
> +#include <fuse_core/ceres_macros.h>
I don't think this is required here

2024-04-03 09:27 UTC, efernandez approved these changes

2024-04-03 12:50 UTC, merged