[RST-2340] Add serialization support to fuse
locusrobotics/fuse pull request #98
Opened 2019-08-22 14:57 UTC by svwilliams

This PR adds serialization to the API of the Variable, Constraint, Graph, and Transaction classes. Support for additional class types can be added as needed.

Additionally, a ROS msgs have been added to transport serialized Graph and Transaction objects using standard ROS comms mechanisms. To demonstrate this ability, a fuse Publisher was created to serialize and publish the updated graph, and a stand alone utility, fuse_echo, was created to subscribe, deserialize, and print the graph.

All commits in this PR have been reviewed independently.

2019-08-23 12:56 UTC, efernandez requested changes

2019-08-23 12:56 UTC, efernandez commented on fuse_publishers/src/serialized_publisher.cpp
> +    msg.header.stamp = stamp;
Could you also set `msg.header.frame_id = "map";`? (same below for the transaction)

I don't know if it's possible to retrieve the frame of the graph / transaction somehow from their classes. If they don't have that field, I think for now this should be fine, or a ROS param to set the frame.

This is important to visualize the graph in `rviz`, for example.

2019-08-26 16:29 UTC, efernandez approved these changes

2019-08-26 17:33 UTC, svwilliams commented
All commits in this PR have been reviewed independently. Merging.

2019-08-26 17:34 UTC, merged